name: Create Lambda Layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - architecture: x86_64
            runner: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: |
        docker buildx build --load --platform linux/${{ matrix.architecture }} --file Dockerfile --tag embulk-legacy-env-${{ matrix.architecture }} .

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: embulk-legacy-env-${{ matrix.architecture }}
        path: embulk-legacy-env-${{ matrix.architecture }}.zip
        retention-days: 1

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: find

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: embulk-legacy-env-x86_64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          body: |
            # Release

            This release contains the Docker image for the embulk-legacy-env-x86_64.